name: ci_meson

on: [workflow_dispatch]
#  push:
#    paths:
#      - "include/*"
#      - "tests/*"
#  pull_request:
#    paths:
#      - "include/*"
#      - "tests/*"
      
jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - uses: ConorMacBride/install-package@v1
      with:
        apt: gcc-13 g++-13
    - run: meson setup builddir/
      env:
        CC: gcc-13
        CXX: g++-13
    - run: meson test -C builddir/ -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: builddir/meson-logs/testlog.txt
